on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Inject GA script
        run: |
          sed -i 's|</html>|<script>console.log("testing")</script></html>|' index.html
      - name: Deploy to GitHub Pages
        uses: github-pages/deploy@v1
